name: Reusable C unit tests

on:
  workflow_call:
    inputs:
      additional-apt-packages:
        description: 'Additional APT packages to install'
        required: false
        type: string
        default: ''
      library-directory:
        description: 'Directory to find the C library'
        required: true
        type: string

jobs:
  c-tests:
    name: C unit tests
    runs-on: ubuntu-24.04

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          submodules: true

      - name: Install system deps 
        run: |
          sudo apt-get update
          sudo apt-get install -y libcunit1-dev libconfig-dev \
            ninja-build valgrind clang  ${{ inputs.additional-apt-packages }}
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.10.2"

      - name: Install uv deps
        run: |
          uv tool install meson==1.10.1
          uv tool install gcovr==8.6

      - name: Configure code
        run: CC=gcc meson setup -Db_coverage=true build-cov ${{ inputs.library-directory }}

      - name: Compile
        run: ninja -C build-cov
      
      - name: Run tests
        run: ninja -C build-cov test

      - name: Build coverage report
        run: ninja -C build-cov coverage-xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: C
          gcov_args: --preserve-paths
          fail_ci_if_error: true
         
      - name: Compile and test with clang
        run: |
          CC=clang meson setup build-clang ${{ inputs.library-directory }}
          ninja -C build-clang test 

      - name: Run tests with valgrind
        run: |
          meson setup build-valgrind ${{ inputs.library-directory }}          
          meson test -C build-valgrind -t-1 \
            --wrapper='valgrind --leak-check=full --error-exitcode=1'
